### ISSUE TITLE
A bunch of L25 links have died

### ISSUE THREAD

**Issue by jzarnett** [jzarnett/ece459#28]
I've run into numerous broken links already... Let's help each other keep track of correct links. I'll begin:
L25: http://google-perftools.googlecode.com/svn/trunk/doc/cpuprofile.html is broken.

L25: http://www.oracle.com/technetwork/server-storage/solarisstudio/documentation/oss-performance-tools-183986.pdf is broken

L25: http://developer.amd.com/assets/AMD_IBS_paper_EN.pdf is broken

L25: http://developer.amd.com/cpu/CodeAnalyst/assets/ISPASS2010_IBS_CA_abstract.pdf is broken

 

Found only some correct links:

http://developer.amd.com/wordpress/media/2012/10/AMD_IBS_paper_EN.pdf

**Comment by marauder00** [comment]
Could this be the new link that debriefs the main Solaris Studio Performance Analyzer features? : https://www.oracle.com/technetwork/server-storage/developerstudio/documentation/o11-151-perf-analyzer-brief-1405338.pdf
